### ISSUE TITLE
If a Text Field's Value is HTML, it breaks stuff

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-field-helpers#20]
Attempted to rebuild the HTML manually in the Inspector and saved in case it was WP All Import that messed things up, but it appears to actually be a rendering issue.

However, I would assume that if it were saved in this borked display state it would then save the borked value.

![image](https://cloud.githubusercontent.com/assets/7770631/23881088/6d8c3a2a-082e-11e7-8921-fe1c555b6574.png)

![image](https://cloud.githubusercontent.com/assets/7770631/23881092/7a6dd082-082e-11e7-9616-138a3f247e1f.png)

**Comment by joelworsham** [comment]
Oh schnikees!!! Red alert!! I must have forgot to escape that field and that is a big security flaw. I'll get that fixed today (not necessarily pushed to all sites, but at least fixed here).

**Comment by d4mation** [comment]
Hm, that's interesting that ACF would have saved the data un-escaped... I had used WP All Export/Import to convert ACF data to use with RBM FH.

So in this case once RBM FH has been patched, I'd need to loop through the data and re-save it?

**Comment by joelworsham** [comment]
It's not really about it being saved escaped, HTML in the DB is fine, it's more about escaping it on output. It's best practice to ALWAYS escape any values that should NOT contain HTML. I forgot to do so is all.

**Comment by d4mation** [comment]
Yeah, I realized that a bit later. Been a long 24 hours :exhausted:

**Comment by d4mation** [comment]
:+1:

![image](https://cloud.githubusercontent.com/assets/7770631/23949141/8145f1d0-095c-11e7-8834-dcb651c9702a.png)
