### ISSUE TITLE
Inconsistencies in callback function for Repeater vs other Field Types

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-field-helpers#22]
Should `$fields` in the Repeater function instead be `$args`? Then if the `$values` and `$args` parameters were swapped around, it would match every other function in the plugin.

As it is now, if you have an Array of Fields that you loop through in order to create Fields using these functions, you need to check if it is a Repeater so you can rearrange the parameters.

https://github.com/realbig/rbm-field-helpers/blob/edc418404c965aa53dcd6f51a91d8008918791ce/includes/rbm-fh-field-functions.php#L184-L214

**Comment by d4mation** [comment]
I know this would be a breaking change for any sites using the `rbm_do_field_repeater()` function, but it would be convenient if it were the same as the others, lol.

**Comment by joelworsham** [comment]
But it's a different parameter. You can still pass `$args` in and it does different stuff. Are you just suggesting changing the order of parameters? So instead of `rbm_do_field_repeater( $name, $values, $fields, $args )`, it would be `rbm_do_field_repeater( $name, $values, $args, $fields )`?

**Comment by d4mation** [comment]
Yeah, changing the order of the parameters.

But `rbm_do_field_repeater()`'s final parameter currently isn't `$args`, it is `$values`.

So if it were re-ordered to be `rbm_do_field_repeater( $name, $label, $values, $args/$fields )` that would bring it to parity with the rest of the callback functions.

In the case of `rbm_do_field_repeater()`, it also uses `$fields` instead of `$args` and then places `$fields` inside of an Array under the `fields` key before creating the Repeater Object. May not be worth it to make it `$args` instead since I don't think the Repeater uses anything else outside of that `field` key, but it would level it out with the rest of the Fields I guess.

**Comment by joelworsham** [comment]
aha, yeah could be worth it. I'd hope to figure out a way to not break legacy though, it's used EVERYWHERE :P

**Comment by d4mation** [comment]
Haha, yeah. I figured. I had not used the Repeater much until yesterday myself. I think the only other time I had used it was handling the WYISWYG within Repeaters Issue.

Breaking legacy would be no bueno for sure.

**Comment by d4mation** [comment]
We broke legacy, lol.
