### ISSUE TITLE
Media JS missing sometimes for Media Field

### ISSUE THREAD

**Issue by d4mation** [realbig/rbm-field-helpers#54]
Not exactly sure why this happened, since I had previously used the Media Field higher up in the page with no problems on an earlier date.

Using `wp_enqueue_media()` fixes it, so maybe that should go above all Media Fields similar to what we did with WYSIWYGs? 

![image](https://user-images.githubusercontent.com/7770631/37838976-b143d358-2e8f-11e8-8f8c-34f20cb109bf.png)

**Comment by d4mation** [comment]
Also, @joelworsham, the JS Errors in RBM FH are fantastic, btw. Immediately clear what went wrong.

**Comment by joelworsham** [comment]
Glad they helped! I wouldn't have considered this a bug. I consider it normal practice to have to enqueue media on admin pages that don't already

**Comment by d4mation** [comment]
Ah, you know what, I know why it worked previously now that you say that! I previously had the default `editor` on screen, but I've since removed it which means `wp_enqueue_media()` is not being ran.

I can close this then. Generally this shouldn't be an issue. If anything, it will just be something to watch out for on Options Pages or weird cases like this where the default `editor` is removed.
